services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential python3-dev
      pip install -r requirements.txt
    startCommand: "python -m gunicorn EQM.asgi:application -k uvicorn.workers.UvicornWorker"